### ISSUE TITLE
issue parsing small json files 

### ISSUE THREAD

**Issue by aymaneMx** [adnanelamghari/big-parsing#2]
I get this error:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
Any idea what I do wrong? Thank you in advance.

**Comment by y-moufakkr** [comment]
d

**Comment by y-moufakkr** [comment]
@aymaneMx FINALLY FOUND THE PRBLM, the repo owner is black, try this [repo]( https://github.com/simdjson/simdjson) it belongs to a white owner, probably this one just copy past the entire project lol

**Comment by younesnajjar** [comment]
What's the problem?

**Comment by y-moufakkr** [comment]
> What's the problem?

the repos owner is black
